[package]
name = "azuki-bot"
edition.workspace = true
version.workspace = true

[dependencies]
azuki-db.workspace = true
azuki-player.workspace = true
azuki-media.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
serenity.workspace = true
songbird.workspace = true
symphonia.workspace = true
sha2.workspace = true
hex.workspace = true
tokio-util.workspace = true
sqlx.workspace = true
url.workspace = true
